name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  go:
    name: Go
    runs-on: ubuntu-23.10
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
          cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
